<?php

namespace AppBundle\Repository;

/**
 * DsCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DsCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
