<?php

namespace AppBundle\Repository;

/**
 * DsImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DsImageRepository extends \Doctrine\ORM\EntityRepository
{
}
