<?php

namespace AppBundle\Repository;

/**
 * DsKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DsKeyRepository extends \Doctrine\ORM\EntityRepository
{
}
