<?php

namespace AppBundle\Repository;

/**
 * DsProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DsProductRepository extends \Doctrine\ORM\EntityRepository
{
}
