<?php

namespace AppBundle\Repository;

/**
 * DsSimilarProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DsSimilarProductRepository extends \Doctrine\ORM\EntityRepository
{
}
